name: Build
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: |
         npm i

      - name: Build
        run: |
          npm run build
          
      - name: Upload IPFS
        env:
         IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
         IPFS_DEPLOY_CLOUDFLARE__ZONE: besoeasy.com
         IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.tailwind.besoeasy.com

        run: |
          npx ipfs-deploy -d cloudflare ./dist
