name: Build
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Init
        run: |
         sudo apt-get update -y 
         sudo apt install git -y

      - name: Install
        run: |
          npm i
          npm run build
          
      - name: Upload
        env:
         IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
         IPFS_DEPLOY_CLOUDFLARE__ZONE: besoeasy.com
         IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.tailwind.besoeasy.com

        run: |
          npx ipfs-deploy -d cloudflare ./dist
